#include <stdio.h>
#include "queue.h"
#include <stdbool.h>
#include "rvvidaemon.h"

int main(){
  int size = 10;
  queue_t * TestQueue;
  TestQueue = InitQueue(size);

  // create a test instruction
  RequiredRVVI_t Instruction0, Instruction1, Instruction2;
  RequiredRVVI_t Instruction3, Instruction4, Instruction5;
  RequiredRVVI_t Instruction6, Instruction7, Instruction8;
  RequiredRVVI_t Instruction9, Instruction10, Instruction11, Instruction12;


  RequiredRVVI_t InstructionRead;

  Instruction0.PC = 0x1000;
  Instruction0.insn = 0x00003197;
  Instruction0.Mcycle = 1;
  Instruction0.Minstret = 1;
  Instruction0.Trap = 0;
  Instruction0.PrivilegeMode = 3;
  Instruction0.GPREn = 1;
  Instruction0.FPREn = 0;
  Instruction0.Pad3 = 0;
  Instruction0.CSRCount = 0;
  Instruction0.Pad4 = 0;
  Instruction0.GPRReg = 1;
  Instruction0.PadG3 = 0;
  Instruction0.GPRValue = 0x4000;
  Instruction0.FPRReg = 0;
  Instruction0.PadF3 = 0;
  Instruction0.FPRValue = 0;
  Instruction0.CSR[0].CSRReg = 0;
  Instruction0.CSR[0].CSRPad = 0;
  Instruction0.CSR[0].CSRValue = 0;
  Instruction0.CSR[1].CSRReg = 0;
  Instruction0.CSR[1].CSRPad = 0;
  Instruction0.CSR[1].CSRValue = 0;
  Instruction0.CSR[2].CSRReg = 0;
  Instruction0.CSR[2].CSRPad = 0;
  Instruction0.CSR[2].CSRValue = 0;
  Instruction0.CSR[3].CSRReg = 0;
  Instruction0.CSR[3].CSRPad = 0;
  Instruction0.CSR[3].CSRValue = 0;
  Instruction0.CSR[4].CSRReg = 0;
  Instruction0.CSR[4].CSRPad = 0;
  Instruction0.CSR[4].CSRValue = 0;

  Instruction1.PC = 0x1004;
  Instruction1.insn = 0x00003198;
  Instruction1.Mcycle = 100;
  Instruction1.Minstret = 2;
  Instruction1.Trap = 0;
  Instruction1.PrivilegeMode = 3;
  Instruction1.GPREn = 1;
  Instruction1.FPREn = 0;
  Instruction1.Pad3 = 0;
  Instruction1.CSRCount = 0;
  Instruction1.Pad4 = 0;
  Instruction1.GPRReg = 1;
  Instruction1.PadG3 = 0;
  Instruction1.GPRValue = 0x4111;
  Instruction1.FPRReg = 0;
  Instruction1.PadF3 = 0;
  Instruction1.FPRValue = 0;
  Instruction1.CSR[0].CSRReg = 0;
  Instruction1.CSR[0].CSRPad = 0;
  Instruction1.CSR[0].CSRValue = 0;
  Instruction1.CSR[1].CSRReg = 0;
  Instruction1.CSR[1].CSRPad = 0;
  Instruction1.CSR[1].CSRValue = 0;
  Instruction1.CSR[2].CSRReg = 0;
  Instruction1.CSR[2].CSRPad = 0;
  Instruction1.CSR[2].CSRValue = 0;
  Instruction1.CSR[3].CSRReg = 0;
  Instruction1.CSR[3].CSRPad = 0;
  Instruction1.CSR[3].CSRValue = 0;
  Instruction1.CSR[4].CSRReg = 0;
  Instruction1.CSR[4].CSRPad = 0;
  Instruction1.CSR[4].CSRValue = 0;

  Instruction2.PC = 0x1008;
  Instruction2.insn = 0xdfadf198;
  Instruction2.Mcycle = 200;
  Instruction2.Minstret = 3;
  Instruction2.Trap = 0;
  Instruction2.PrivilegeMode = 3;
  Instruction2.GPREn = 1;
  Instruction2.FPREn = 0;
  Instruction2.Pad3 = 0;
  Instruction2.CSRCount = 0;
  Instruction2.Pad4 = 0;
  Instruction2.GPRReg = 1;
  Instruction2.PadG3 = 0;
  Instruction2.GPRValue = 0x5111;
  Instruction2.FPRReg = 0;
  Instruction2.PadF3 = 0;
  Instruction2.FPRValue = 0;
  Instruction2.CSR[0].CSRReg = 0;
  Instruction2.CSR[0].CSRPad = 0;
  Instruction2.CSR[0].CSRValue = 0;
  Instruction2.CSR[1].CSRReg = 0;
  Instruction2.CSR[1].CSRPad = 0;
  Instruction2.CSR[1].CSRValue = 0;
  Instruction2.CSR[2].CSRReg = 0;
  Instruction2.CSR[2].CSRPad = 0;
  Instruction2.CSR[2].CSRValue = 0;
  Instruction2.CSR[3].CSRReg = 0;
  Instruction2.CSR[3].CSRPad = 0;
  Instruction2.CSR[3].CSRValue = 0;
  Instruction2.CSR[4].CSRReg = 0;
  Instruction2.CSR[4].CSRPad = 0;
  Instruction2.CSR[4].CSRValue = 0;

  Instruction3.PC = 0x100C;
  Instruction3.insn = 0xdfadf198;
  Instruction3.Mcycle = 300;
  Instruction3.Minstret = 4;
  Instruction3.Trap = 0;
  Instruction3.PrivilegeMode = 3;
  Instruction3.GPREn = 1;
  Instruction3.FPREn = 0;
  Instruction3.Pad3 = 0;
  Instruction3.CSRCount = 0;
  Instruction3.Pad4 = 0;
  Instruction3.GPRReg = 1;
  Instruction3.PadG3 = 0;
  Instruction3.GPRValue = 0x5111;
  Instruction3.FPRReg = 0;
  Instruction3.PadF3 = 0;
  Instruction3.FPRValue = 0;
  Instruction3.CSR[0].CSRReg = 0;
  Instruction3.CSR[0].CSRPad = 0;
  Instruction3.CSR[0].CSRValue = 0;
  Instruction3.CSR[1].CSRReg = 0;
  Instruction3.CSR[1].CSRPad = 0;
  Instruction3.CSR[1].CSRValue = 0;
  Instruction3.CSR[2].CSRReg = 0;
  Instruction3.CSR[2].CSRPad = 0;
  Instruction3.CSR[2].CSRValue = 0;
  Instruction3.CSR[3].CSRReg = 0;
  Instruction3.CSR[3].CSRPad = 0;
  Instruction3.CSR[3].CSRValue = 0;
  Instruction3.CSR[4].CSRReg = 0;
  Instruction3.CSR[4].CSRPad = 0;
  Instruction3.CSR[4].CSRValue = 0;

  Instruction4.PC = 0x1010;
  Instruction4.insn = 0xdfadf198;
  Instruction4.Mcycle = 400;
  Instruction4.Minstret = 5;
  Instruction4.Trap = 0;
  Instruction4.PrivilegeMode = 3;
  Instruction4.GPREn = 1;
  Instruction4.FPREn = 0;
  Instruction4.Pad3 = 0;
  Instruction4.CSRCount = 0;
  Instruction4.Pad4 = 0;
  Instruction4.GPRReg = 1;
  Instruction4.PadG3 = 0;
  Instruction4.GPRValue = 0x5111;
  Instruction4.FPRReg = 0;
  Instruction4.PadF3 = 0;
  Instruction4.FPRValue = 0;
  Instruction4.CSR[0].CSRReg = 0;
  Instruction4.CSR[0].CSRPad = 0;
  Instruction4.CSR[0].CSRValue = 0;
  Instruction4.CSR[1].CSRReg = 0;
  Instruction4.CSR[1].CSRPad = 0;
  Instruction4.CSR[1].CSRValue = 0;
  Instruction4.CSR[2].CSRReg = 0;
  Instruction4.CSR[2].CSRPad = 0;
  Instruction4.CSR[2].CSRValue = 0;
  Instruction4.CSR[3].CSRReg = 0;
  Instruction4.CSR[3].CSRPad = 0;
  Instruction4.CSR[3].CSRValue = 0;
  Instruction4.CSR[4].CSRReg = 0;
  Instruction4.CSR[4].CSRPad = 0;
  Instruction4.CSR[4].CSRValue = 0;
  
  Instruction5.PC = 0x1014;
  Instruction5.insn = 0xdfadf198;
  Instruction5.Mcycle = 500;
  Instruction5.Minstret = 6;
  Instruction5.Trap = 0;
  Instruction5.PrivilegeMode = 3;
  Instruction5.GPREn = 1;
  Instruction5.FPREn = 0;
  Instruction5.Pad3 = 0;
  Instruction5.CSRCount = 0;
  Instruction5.Pad4 = 0;
  Instruction5.GPRReg = 1;
  Instruction5.PadG3 = 0;
  Instruction5.GPRValue = 0x5111;
  Instruction5.FPRReg = 0;
  Instruction5.PadF3 = 0;
  Instruction5.FPRValue = 0;
  Instruction5.CSR[0].CSRReg = 0;
  Instruction5.CSR[0].CSRPad = 0;
  Instruction5.CSR[0].CSRValue = 0;
  Instruction5.CSR[1].CSRReg = 0;
  Instruction5.CSR[1].CSRPad = 0;
  Instruction5.CSR[1].CSRValue = 0;
  Instruction5.CSR[2].CSRReg = 0;
  Instruction5.CSR[2].CSRPad = 0;
  Instruction5.CSR[2].CSRValue = 0;
  Instruction5.CSR[3].CSRReg = 0;
  Instruction5.CSR[3].CSRPad = 0;
  Instruction5.CSR[3].CSRValue = 0;
  Instruction5.CSR[4].CSRReg = 0;
  Instruction5.CSR[4].CSRPad = 0;
  Instruction5.CSR[4].CSRValue = 0;

  Instruction6.PC = 0x1018;
  Instruction6.insn = 0xdfadf198;
  Instruction6.Mcycle = 600;
  Instruction6.Minstret = 7;
  Instruction6.Trap = 0;
  Instruction6.PrivilegeMode = 3;
  Instruction6.GPREn = 1;
  Instruction6.FPREn = 0;
  Instruction6.Pad3 = 0;
  Instruction6.CSRCount = 0;
  Instruction6.Pad4 = 0;
  Instruction6.GPRReg = 1;
  Instruction6.PadG3 = 0;
  Instruction6.GPRValue = 0x5111;
  Instruction6.FPRReg = 0;
  Instruction6.PadF3 = 0;
  Instruction6.FPRValue = 0;
  Instruction6.CSR[0].CSRReg = 0;
  Instruction6.CSR[0].CSRPad = 0;
  Instruction6.CSR[0].CSRValue = 0;
  Instruction6.CSR[1].CSRReg = 0;
  Instruction6.CSR[1].CSRPad = 0;
  Instruction6.CSR[1].CSRValue = 0;
  Instruction6.CSR[2].CSRReg = 0;
  Instruction6.CSR[2].CSRPad = 0;
  Instruction6.CSR[2].CSRValue = 0;
  Instruction6.CSR[3].CSRReg = 0;
  Instruction6.CSR[3].CSRPad = 0;
  Instruction6.CSR[3].CSRValue = 0;
  Instruction6.CSR[4].CSRReg = 0;
  Instruction6.CSR[4].CSRPad = 0;
  Instruction6.CSR[4].CSRValue = 0;

  Instruction7.PC = 0x1020;
  Instruction7.insn = 0xdfadf198;
  Instruction7.Mcycle = 700;
  Instruction7.Minstret = 8;
  Instruction7.Trap = 0;
  Instruction7.PrivilegeMode = 3;
  Instruction7.GPREn = 1;
  Instruction7.FPREn = 0;
  Instruction7.Pad3 = 0;
  Instruction7.CSRCount = 0;
  Instruction7.Pad4 = 0;
  Instruction7.GPRReg = 1;
  Instruction7.PadG3 = 0;
  Instruction7.GPRValue = 0x5111;
  Instruction7.FPRReg = 0;
  Instruction7.PadF3 = 0;
  Instruction7.FPRValue = 0;
  Instruction7.CSR[0].CSRReg = 0;
  Instruction7.CSR[0].CSRPad = 0;
  Instruction7.CSR[0].CSRValue = 0;
  Instruction7.CSR[1].CSRReg = 0;
  Instruction7.CSR[1].CSRPad = 0;
  Instruction7.CSR[1].CSRValue = 0;
  Instruction7.CSR[2].CSRReg = 0;
  Instruction7.CSR[2].CSRPad = 0;
  Instruction7.CSR[2].CSRValue = 0;
  Instruction7.CSR[3].CSRReg = 0;
  Instruction7.CSR[3].CSRPad = 0;
  Instruction7.CSR[3].CSRValue = 0;
  Instruction7.CSR[4].CSRReg = 0;
  Instruction7.CSR[4].CSRPad = 0;
  Instruction7.CSR[4].CSRValue = 0;
  
  Instruction8.PC = 0x1024;
  Instruction8.insn = 0xdfadf198;
  Instruction8.Mcycle = 800;
  Instruction8.Minstret = 9;
  Instruction8.Trap = 0;
  Instruction8.PrivilegeMode = 3;
  Instruction8.GPREn = 1;
  Instruction8.FPREn = 0;
  Instruction8.Pad3 = 0;
  Instruction8.CSRCount = 0;
  Instruction8.Pad4 = 0;
  Instruction8.GPRReg = 1;
  Instruction8.PadG3 = 0;
  Instruction8.GPRValue = 0x5111;
  Instruction8.FPRReg = 0;
  Instruction8.PadF3 = 0;
  Instruction8.FPRValue = 0;
  Instruction8.CSR[0].CSRReg = 0;
  Instruction8.CSR[0].CSRPad = 0;
  Instruction8.CSR[0].CSRValue = 0;
  Instruction8.CSR[1].CSRReg = 0;
  Instruction8.CSR[1].CSRPad = 0;
  Instruction8.CSR[1].CSRValue = 0;
  Instruction8.CSR[2].CSRReg = 0;
  Instruction8.CSR[2].CSRPad = 0;
  Instruction8.CSR[2].CSRValue = 0;
  Instruction8.CSR[3].CSRReg = 0;
  Instruction8.CSR[3].CSRPad = 0;
  Instruction8.CSR[3].CSRValue = 0;
  Instruction8.CSR[4].CSRReg = 0;
  Instruction8.CSR[4].CSRPad = 0;
  Instruction8.CSR[4].CSRValue = 0;

  Instruction9.PC = 0x1028;
  Instruction9.insn = 0xdfadf198;
  Instruction9.Mcycle = 900;
  Instruction9.Minstret = 10;
  Instruction9.Trap = 0;
  Instruction9.PrivilegeMode = 3;
  Instruction9.GPREn = 1;
  Instruction9.FPREn = 0;
  Instruction9.Pad3 = 0;
  Instruction9.CSRCount = 0;
  Instruction9.Pad4 = 0;
  Instruction9.GPRReg = 1;
  Instruction9.PadG3 = 0;
  Instruction9.GPRValue = 0x5111;
  Instruction9.FPRReg = 0;
  Instruction9.PadF3 = 0;
  Instruction9.FPRValue = 0;
  Instruction9.CSR[0].CSRReg = 0;
  Instruction9.CSR[0].CSRPad = 0;
  Instruction9.CSR[0].CSRValue = 0;
  Instruction9.CSR[1].CSRReg = 0;
  Instruction9.CSR[1].CSRPad = 0;
  Instruction9.CSR[1].CSRValue = 0;
  Instruction9.CSR[2].CSRReg = 0;
  Instruction9.CSR[2].CSRPad = 0;
  Instruction9.CSR[2].CSRValue = 0;
  Instruction9.CSR[3].CSRReg = 0;
  Instruction9.CSR[3].CSRPad = 0;
  Instruction9.CSR[3].CSRValue = 0;
  Instruction9.CSR[4].CSRReg = 0;
  Instruction9.CSR[4].CSRPad = 0;
  Instruction9.CSR[4].CSRValue = 0;

  Instruction10.PC = 0x102C;
  Instruction10.insn = 0xdfadf198;
  Instruction10.Mcycle = 1000;
  Instruction10.Minstret = 11;
  Instruction10.Trap = 0;
  Instruction10.PrivilegeMode = 3;
  Instruction10.GPREn = 1;
  Instruction10.FPREn = 0;
  Instruction10.Pad3 = 0;
  Instruction10.CSRCount = 0;
  Instruction10.Pad4 = 0;
  Instruction10.GPRReg = 1;
  Instruction10.PadG3 = 0;
  Instruction10.GPRValue = 0x5111;
  Instruction10.FPRReg = 0;
  Instruction10.PadF3 = 0;
  Instruction10.FPRValue = 0;
  Instruction10.CSR[0].CSRReg = 0;
  Instruction10.CSR[0].CSRPad = 0;
  Instruction10.CSR[0].CSRValue = 0;
  Instruction10.CSR[1].CSRReg = 0;
  Instruction10.CSR[1].CSRPad = 0;
  Instruction10.CSR[1].CSRValue = 0;
  Instruction10.CSR[2].CSRReg = 0;
  Instruction10.CSR[2].CSRPad = 0;
  Instruction10.CSR[2].CSRValue = 0;
  Instruction10.CSR[3].CSRReg = 0;
  Instruction10.CSR[3].CSRPad = 0;
  Instruction10.CSR[3].CSRValue = 0;
  Instruction10.CSR[4].CSRReg = 0;
  Instruction10.CSR[4].CSRPad = 0;
  Instruction10.CSR[4].CSRValue = 0;

  Instruction11.PC = 0x1030;
  Instruction11.insn = 0xdfadf198;
  Instruction11.Mcycle = 1100;
  Instruction11.Minstret = 12;
  Instruction11.Trap = 0;
  Instruction11.PrivilegeMode = 3;
  Instruction11.GPREn = 1;
  Instruction11.FPREn = 0;
  Instruction11.Pad3 = 0;
  Instruction11.CSRCount = 0;
  Instruction11.Pad4 = 0;
  Instruction11.GPRReg = 1;
  Instruction11.PadG3 = 0;
  Instruction11.GPRValue = 0x5111;
  Instruction11.FPRReg = 0;
  Instruction11.PadF3 = 0;
  Instruction11.FPRValue = 0;
  Instruction11.CSR[0].CSRReg = 0;
  Instruction11.CSR[0].CSRPad = 0;
  Instruction11.CSR[0].CSRValue = 0;
  Instruction11.CSR[1].CSRReg = 0;
  Instruction11.CSR[1].CSRPad = 0;
  Instruction11.CSR[1].CSRValue = 0;
  Instruction11.CSR[2].CSRReg = 0;
  Instruction11.CSR[2].CSRPad = 0;
  Instruction11.CSR[2].CSRValue = 0;
  Instruction11.CSR[3].CSRReg = 0;
  Instruction11.CSR[3].CSRPad = 0;
  Instruction11.CSR[3].CSRValue = 0;
  Instruction11.CSR[4].CSRReg = 0;
  Instruction11.CSR[4].CSRPad = 0;
  Instruction11.CSR[4].CSRValue = 0;

  Instruction12.PC = 0x1034;
  Instruction12.insn = 0xdfadf198;
  Instruction12.Mcycle = 1200;
  Instruction12.Minstret = 13;
  Instruction12.Trap = 0;
  Instruction12.PrivilegeMode = 3;
  Instruction12.GPREn = 1;
  Instruction12.FPREn = 0;
  Instruction12.Pad3 = 0;
  Instruction12.CSRCount = 0;
  Instruction12.Pad4 = 0;
  Instruction12.GPRReg = 1;
  Instruction12.PadG3 = 0;
  Instruction12.GPRValue = 0x5111;
  Instruction12.FPRReg = 0;
  Instruction12.PadF3 = 0;
  Instruction12.FPRValue = 0;
  Instruction12.CSR[0].CSRReg = 0;
  Instruction12.CSR[0].CSRPad = 0;
  Instruction12.CSR[0].CSRValue = 0;
  Instruction12.CSR[1].CSRReg = 0;
  Instruction12.CSR[1].CSRPad = 0;
  Instruction12.CSR[1].CSRValue = 0;
  Instruction12.CSR[2].CSRReg = 0;
  Instruction12.CSR[2].CSRPad = 0;
  Instruction12.CSR[2].CSRValue = 0;
  Instruction12.CSR[3].CSRReg = 0;
  Instruction12.CSR[3].CSRPad = 0;
  Instruction12.CSR[3].CSRValue = 0;
  Instruction12.CSR[4].CSRReg = 0;
  Instruction12.CSR[4].CSRPad = 0;
  Instruction12.CSR[4].CSRValue = 0;

  printf("Start\n\n");
  PrintValidQueue(TestQueue);
  printf("\n");


  printf("Add first instruction\n\n");
  Enqueue(&Instruction0, TestQueue);
  PrintValidQueue(TestQueue);
  printf("\n");
  

  printf("Remove first instruction\n\n");
  Dequeue(&InstructionRead, TestQueue);
  PrintValidQueue(TestQueue);
  printf("\n");

  printf("Add 1 instruction\n\n");
  Enqueue(&Instruction1, TestQueue);
  PrintValidQueue(TestQueue);
  printf("\n");

  printf("Add 1 instruction\n\n");
  Enqueue(&Instruction2, TestQueue);
  PrintValidQueue(TestQueue);
  printf("\n");


  printf("Add two instructions total 4.\n\n");
  Enqueue(&Instruction3, TestQueue);
  Enqueue(&Instruction4, TestQueue);
  PrintValidQueue(TestQueue);
  printf("Is Almost Full? %d\n", IsAlmostFull(TestQueue, 7));
  printf("\n");

  printf("Add 4 instructions total 8.\n\n");
  Enqueue(&Instruction5, TestQueue);
  Enqueue(&Instruction6, TestQueue);
  Enqueue(&Instruction7, TestQueue);
  Enqueue(&Instruction8, TestQueue);

  PrintValidQueue(TestQueue);
  printf("\n");

  
  printf("Add 1 instruction total 9. Causes wrap around\n\n");
  Enqueue(&Instruction9, TestQueue);
  PrintValidQueue(TestQueue);
  printf("Is Full? %d\n", IsFull(TestQueue));
  printf("Is Almost Full? %d\n", IsAlmostFull(TestQueue, 7));
  printf("\n");

  printf("Got here!!!!!!!!!!!!!!!!!!!!!! Almost full\n");
  printf("\n");

  printf("Add 1 instruction total 10. Now Full\n\n");
  Enqueue(&Instruction10, TestQueue);
  PrintValidQueue(TestQueue);
  printf("Is Full? %d\n", IsFull(TestQueue));
  printf("Is Almost Full? %d\n", IsAlmostFull(TestQueue, 7));
  printf("\n");

  printf("REmove 1 instruction total 9.\n\n");
  Dequeue(&InstructionRead, TestQueue);
  PrintValidQueue(TestQueue);
  printf("Is Full? %d\n", IsFull(TestQueue));
  printf("Is Almost Full? %d\n", IsAlmostFull(TestQueue, 7));
  printf("\n");

  printf("Add 1 instruction total 10. Now Full\n\n");
  Enqueue(&Instruction11, TestQueue);
  PrintValidQueue(TestQueue);
  printf("Is Full? %d\n", IsFull(TestQueue));
  printf("Is Almost Full? %d\n", IsAlmostFull(TestQueue, 7));
  printf("\n");

  printf("REmove 1 instruction total 9.\n\n");
  Dequeue(&InstructionRead, TestQueue);
  PrintValidQueue(TestQueue);
  printf("Is Full? %d\n", IsFull(TestQueue));
  printf("Is Almost Full? %d\n", IsAlmostFull(TestQueue, 7));
  printf("\n");
  
  printf("Add 1 instruction total 10. Now Full\n\n");
  Enqueue(&Instruction12, TestQueue);
  PrintValidQueue(TestQueue);
  printf("Is Full? %d\n", IsFull(TestQueue));
  printf("Is Almost Full? %d\n", IsAlmostFull(TestQueue, 7));
  printf("\n");
  
  printf("Add 1 instruction total 10. Can't actually add anything just ignored\n\n");
  Enqueue(&Instruction1, TestQueue);
  PrintValidQueue(TestQueue);
  printf("Is Full? %d\n", IsFull(TestQueue));
  printf("Is Almost Full? %d\n", IsAlmostFull(TestQueue, 7));
  printf("\n");

}
